version: 1.2
workflows:
  - subclass: WDL
  primaryDescriptorPath: /fusions_manta/fusions.wdl
  testParameterFiles: /fusions_manta/fusion_inputs.json
  authors:
    - name: Jonathan Tang
    - email: jonathanztang@wustl.edu
